CREATE TABLE IF NOT EXISTS raw.fds (
    ingest_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_file text NOT NULL,
    source_row bigint NOT NULL CHECK (source_row > 0),
    recno bigint,
    source_id text,
    ra_j2000 double precision,
    dec_j2000 double precision,
    u_mag double precision,
    u_mag_err double precision,
    g_mag double precision,
    g_mag_err double precision,
    r_mag double precision,
    r_mag_err double precision,
    i_mag double precision,
    i_mag_err double precision,
    class_star double precision,
    concentration double precision,
    flux_radius_arcsec double precision,
    fwhm_arcsec double precision,
    major_rms_deg double precision,
    minor_rms_deg double precision,
    elongation double precision,
    flags integer,
    sharpness double precision,
    u_class_star double precision,
    u_concentration double precision,
    u_sharpness double precision,
    u_mag_ap8 double precision,
    u_mag_ap8_err double precision,
    u_mag_auto double precision,
    u_mag_auto_err double precision,
    g_class_star double precision,
    g_concentration double precision,
    g_sharpness double precision,
    g_mag_ap8 double precision,
    g_mag_ap8_err double precision,
    g_mag_auto double precision,
    g_mag_auto_err double precision,
    r_class_star double precision,
    r_concentration double precision,
    r_sharpness double precision,
    r_mag_ap8 double precision,
    r_mag_ap8_err double precision,
    r_mag_auto double precision,
    r_mag_auto_err double precision,
    i_class_star double precision,
    i_concentration double precision,
    i_sharpness double precision,
    i_mag_ap8 double precision,
    i_mag_ap8_err double precision,
    i_mag_auto double precision,
    i_mag_auto_err double precision,
    ebv double precision,
    field_id smallint,
    loaded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_file, source_row)
);

CREATE INDEX IF NOT EXISTS fds_source_id_idx ON raw.fds (source_id);
CREATE INDEX IF NOT EXISTS fds_sky_idx ON raw.fds (ra_j2000, dec_j2000);

CREATE TABLE IF NOT EXISTS raw.des (
    ingest_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_file text NOT NULL,
    source_row bigint NOT NULL CHECK (source_row > 0),
    coadd_object_id bigint,
    ra double precision,
    dec double precision,
    ra_window double precision,
    dec_window double precision,
    extended_class_coadd smallint,
    extended_class_wavg smallint,
    ebv_sfd98 double precision,
    i_mag_auto double precision,
    i_mag_auto_dered double precision,
    i_spread_model double precision,
    i_spread_model_err double precision,
    i_class_star double precision,
    i_flux_radius double precision,
    i_fwhm_image double precision,
    i_flags integer,
    i_image_flags_iso integer,
    g_mag_ap5 double precision,
    g_mag_ap5_err double precision,
    r_mag_ap5 double precision,
    r_mag_ap5_err double precision,
    i_mag_ap5 double precision,
    i_mag_ap5_err double precision,
    z_mag_ap5 double precision,
    z_mag_ap5_err double precision,
    y_mag_ap5 double precision,
    y_mag_ap5_err double precision,
    loaded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_file, source_row)
);

CREATE INDEX IF NOT EXISTS des_object_id_idx ON raw.des (coadd_object_id);
CREATE INDEX IF NOT EXISTS des_sky_idx ON raw.des (ra_window, dec_window);

CREATE TABLE IF NOT EXISTS raw.gc_master (
    ingest_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_file text NOT NULL,
    source_row bigint NOT NULL CHECK (source_row > 0),
    source_id text,
    ra_deg double precision,
    dec_deg double precision,
    u_mag double precision,
    u_mag_err double precision,
    g_mag double precision,
    g_mag_err double precision,
    r_mag double precision,
    r_mag_err double precision,
    i_mag double precision,
    i_mag_err double precision,
    class_star double precision,
    concentration double precision,
    flux_radius_arcsec double precision,
    fwhm_arcsec double precision,
    elongation double precision,
    sharpness double precision,
    ebv double precision,
    field_id smallint,
    fcc text,
    p_gc double precision,
    half_light_radius double precision,
    photometric_flag text,
    spectroscopic_flag text,
    loaded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_file, source_row)
);

CREATE INDEX IF NOT EXISTS gc_master_source_id_idx
    ON raw.gc_master (source_id);
CREATE INDEX IF NOT EXISTS gc_master_sky_idx
    ON raw.gc_master (ra_deg, dec_deg);

CREATE TABLE IF NOT EXISTS raw.spec (
    ingest_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_file text NOT NULL,
    source_row bigint NOT NULL CHECK (source_row > 0),
    point_name text,
    fvss_gc text,
    ra_deg double precision,
    dec_deg double precision,
    radial_velocity double precision,
    radial_velocity_err double precision,
    signal_to_noise double precision,
    source_class text,
    fds_id text,
    fiber_ra_deg double precision,
    fiber_dec_deg double precision,
    g_mag double precision,
    g_mag_err double precision,
    r_mag double precision,
    r_mag_err double precision,
    i_mag double precision,
    i_mag_err double precision,
    u_mag double precision,
    u_mag_err double precision,
    loaded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_file, source_row)
);

CREATE INDEX IF NOT EXISTS spec_fds_id_idx ON raw.spec (fds_id);
CREATE INDEX IF NOT EXISTS spec_sky_idx ON raw.spec (ra_deg, dec_deg);
