\set ON_ERROR_STOP on

BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = 'gc_raw_owner'
    ) THEN
        CREATE ROLE gc_raw_owner NOLOGIN;
    END IF;
END
$$;

ALTER ROLE gc_raw_owner
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
REVOKE gc_raw_owner FROM gc;

ALTER SCHEMA raw OWNER TO gc_raw_owner;
ALTER TABLE raw.fds OWNER TO gc_raw_owner;
ALTER TABLE raw.des OWNER TO gc_raw_owner;
ALTER TABLE raw.gc_master OWNER TO gc_raw_owner;
ALTER TABLE raw.spec OWNER TO gc_raw_owner;

REVOKE ALL PRIVILEGES ON SCHEMA raw FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SCHEMA raw FROM gc;
GRANT USAGE ON SCHEMA raw TO gc;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA raw FROM PUBLIC;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA raw FROM gc;
GRANT SELECT ON ALL TABLES IN SCHEMA raw TO gc;

ALTER DEFAULT PRIVILEGES FOR ROLE gc_raw_owner IN SCHEMA raw
    REVOKE ALL PRIVILEGES ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE gc_raw_owner IN SCHEMA raw
    GRANT SELECT ON TABLES TO gc;

COMMIT;
